# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_emax6_0_0/design_1_emax6_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_emax6_0_0 || ORIG_REF_NAME==design_1_emax6_0_0} -quiet] -quiet

# IP: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_emax6_0_0/src/fpga_bram64/fpga_bram64.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_bram64 || ORIG_REF_NAME==fpga_bram64} -quiet] -quiet

# IP: bd/design_1/ip/design_1_versal_cips_0_0/design_1_versal_cips_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_versal_cips_0_0 || ORIG_REF_NAME==design_1_versal_cips_0_0} -quiet] -quiet

# Block Designs: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_versal_cips_0_0/bd_0/bd_70da.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_70da || ORIG_REF_NAME==bd_70da} -quiet] -quiet

# IP: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_versal_cips_0_0/bd_0/ip/ip_0/bd_70da_pspmc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_70da_pspmc_0_0 || ORIG_REF_NAME==bd_70da_pspmc_0_0} -quiet] -quiet

# IP: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_versal_cips_0_0/bd_0/ip/ip_0/ip_0/versal_cips_ps_vip_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_cips_ps_vip_0 || ORIG_REF_NAME==versal_cips_ps_vip_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_1_0 || ORIG_REF_NAME==design_1_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wizard_0_0/design_1_clk_wizard_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wizard_0_0 || ORIG_REF_NAME==design_1_clk_wizard_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_0_0/design_1_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_0 || ORIG_REF_NAME==design_1_smartconnect_0_0} -quiet] -quiet

# Block Designs: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/bd_48ac.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_0/bd_48ac_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_48ac_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_48ac_psr_aclk1_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/bd_48ac_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/bd_48ac_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/bd_48ac_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_7/bd_48ac_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_8/bd_48ac_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_9/bd_48ac_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_10/bd_48ac_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_11/bd_48ac_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_12/bd_48ac_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_13/bd_48ac_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_14/bd_48ac_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_emax6_0_0/src/fpga_bram64/fpga_bram64_waivers.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fpga_bram64 || ORIG_REF_NAME==fpga_bram64} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_emax6_0_0/src/fpga_bram64/fpga_bram64_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_versal_cips_0_0/bd_0/ip/ip_0/bd_70da_pspmc_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_70da_pspmc_0_0 || ORIG_REF_NAME==bd_70da_pspmc_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_versal_cips_0_0/bd_0/ip/ip_0/pspmc_v1_1/constraints/usr_constraints.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_70da_pspmc_0_0 || ORIG_REF_NAME==bd_70da_pspmc_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_versal_cips_0_0/bd_0/bd_70da_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_1_0 || ORIG_REF_NAME==design_1_proc_sys_reset_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_1_0 || ORIG_REF_NAME==design_1_proc_sys_reset_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_clk_wizard_0_0/design_1_clk_wizard_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wizard_0_0 || ORIG_REF_NAME==design_1_clk_wizard_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_clk_wizard_0_0/design_1_clk_wizard_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wizard_0_0 || ORIG_REF_NAME==design_1_clk_wizard_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_clk_wizard_0_0/design_1_clk_wizard_0_0_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_48ac_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_48ac_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_48ac_psr_aclk1_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_48ac_psr_aclk1_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_7/bd_48ac_s00a2s_0_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_8/bd_48ac_sarn_0_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_9/bd_48ac_srn_0_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_10/bd_48ac_sawn_0_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_11/bd_48ac_swn_0_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_12/bd_48ac_sbn_0_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_13/bd_48ac_m00s2a_0_ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/ooc.xdc

# XDC: /home/nakashim/proj-arm64/fpga/VMK180-step4000/VMK180_32st.gen/sources_1/bd/design_1/design_1_ooc.xdc
